inputs:
  #############################
  # Security Settings
  #############################
  security_enabled:
    default: false

  ssl_enabled:
    default: false

  admin_username:
    default: admin

  admin_password:
    default: admin

  insecure_endpoints_disabled:
    description: Disables insecure REST endpoints
    type: boolean
    default: false

  #############################
  # Bootstrap Validations
  #############################
  ignore_bootstrap_validations:
    description: >
      While validations will be performed, they will be ignored.
    type: string
    default: false

  minimum_required_total_physical_memory_in_mb:
    description: Minimum required physical memory on Manager host in MB.
    type: integer
    default: 3792

  minimum_required_available_disk_space_in_gb:
    description: Minimum required disk space on Manager host in GB.
    type: integer
    default: 5

  allowed_heap_size_gap_in_mb:
    description: Gap between heap size and total Manager host's memory in MB.
    type: integer
    default: 1000


  #############################
  # RabbitMQ Inputs
  #############################

  rabbitmq_endpoint_ip:
    description: >
      Location of the rabbit server. If blank, the manager IP will be used.
      Note that if this is set, the external rabbit service must already exist with the appropriate
      credentials and configuration.
      If this is set, rabbit will not be installed on the manager. This may have security implications
      if you are using SSL for rabbit as some normally internal (to the manager) traffic is not currently
      encrypted.
    type: string
    default: ''

  rabbitmq_events_queue_message_ttl:
    description: >
      Sets the number of milliseconds to wait before a message expires
      in the events queue.
      Not used if an external endpoint is used.
    type: integer
    default: 60000

  rabbitmq_logs_queue_message_ttl:
    description: >
      Sets the number of milliseconds to wait before a message expires
      in the logs queue.
      Not used if an external endpoint is used.
    type: integer
    default: 60000

  rabbitmq_metrics_queue_message_ttl:
    description: >
      Sets the number of milliseconds to wait before a message expires
      in the metrics queues.
      Not used if an external endpoint is used.
    type: integer
    default: 60000

  rabbitmq_username:
    description: >
      Sets the username to use for clients such as celery to connect to the rabbitmq broker.
      It is recommended that you set both the username and password to something reasonably secure.
    type: string
    default: cloudify

  rabbitmq_password:
    description: >
      Sets the password to use for clients such as celery to connect to the rabbitmq broker.
      It is recommended that you set both the username and password to something reasonably secure.
    type: string
    default: c10udify

  rabbitmq_ssl_enabled:
    description: >
      Whether SSL should be enabled for RabbitMQ. If this is set to true then the public and private
      certs must be supplied (rabbitmq_cert_private, rabbitmq_cert_public inputs).
    type: boolean
    default: false

  rabbitmq_cert_private:
    description: >
      The private certificate for RabbitMQ to use for SSL. This must be PEM formatted.
      It is expected to begin with a line containing 'PRIVATE KEY' in the middle.
      Not used if an external endpoint is used.
    type: string
    default: ''

  rabbitmq_cert_public:
    description: >
      The public certificate for RabbitMQ to use for SSL. This does not need to be signed by any CA,
      as it will be deployed and explicitly used for all other components.
      It may be self-signed. It must be PEM formatted.
      It is expected to begin with a line of dashes with 'BEGIN CERTIFICATE' in the middle.
      If an external endpoint is used, this must be the public certificate associated with the private
      certificate that has already been configured for use by that rabbit endpoint.
    type: string
    default: ''

  # note that for each of the queue length limit properties, new messages
  # will be queued in RabbitMQ and old messages will be deleted once the
  # limit is reached!
  # https://www.rabbitmq.com/maxlength.html
  rabbitmq_events_queue_length_limit:
    description: >
      Sets the number of messages the events queue can hold.
      Note this is NOT the message byte length!
      Not used if an external endpoint is used.
    type: integer
    default: 1000000

  rabbitmq_logs_queue_length_limit:
    description: >
      Sets the number of messages the logs queue can hold.
      Note this is NOT the message byte length!
      Not used if an external endpoint is used.
    type: integer
    default: 1000000

  rabbitmq_metrics_queue_length_limit:
    description: >
      Sets the number of messages the metrics queues can hold.
      This applies to both the queue that amqp-influx pulls from and
      the ones Riemann pulls from.
      Note this is NOT the message byte length!
      Not used if an external endpoint is used.
    type: integer
    default: 1000000

  rabbitmq_fd_limit:
    description: >
      Sets the File Descriptor limit for the rabbitmq user.
      Not used if an external endpoint is used.
    type: integer
    default: 102400

  #############################
  # Management Workers Inputs
  #############################

  management_worker_log_level:
    description: >
      Sets the logging level to use for the management workers. This affects the logging performed
      by the manager during the execution of management tasks, such as deployment creation
      and deployment deletion.
      NOTE: specifying "debug" will result in considerable amount of logging activity. Consider
      using "info" (or a more restrictive level) for production environments.
    type: string
    default: debug

  #############################
  # Elasticsearch Inputs
  #############################
  # https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html
  elasticsearch_heap_size:
    type: string
    default: "2g"

  elasticsearch_java_opts:
    description: >
      Provide any JAVA_OPTS to Elasticsearch.
    type: string
    default: ''

  # The index for events/logs will be named `logstash-YYYY.mm.dd` and
  # A new index corresponding with today's date will be added each day.
  # Elasticsearch Curator is used to rotate the indices on a daily basis
  # via a cronjob.
  # https://www.elastic.co/blog/curator-tending-your-time-series-indices
  elasticsearch_index_rotation_interval:
    description: >
      Determines the number of days to keep.
    type: integer
    default: 7

  elasticsearch_endpoint_ip:
    description: >
      An IP Endpoint of your Elasticsearch Cluster.
    type: string
    default: ''

  elasticsearch_endpoint_port:
    description: >
      The Port of your Elasticsearch Cluster.
    type: integer
    default: 9200

  elasticsearch_clustering_enabled:
    description: >
      Whether to enable automatic clustering of elasticsearch nodes via multicast discovery.
      This can be either 'true' or 'false'
    type: string
    default: 'false'

  elasticsearch_clustering_discovery_port:
    description: >
      The port used to discover other elasticsearch nodes on the same network.
      Note that the default in elasticsearch's configuration is 54328. Here we default to
      another port to prevent accidental discovery of already installed node within the
      same network.
    type: integer
    default: 54329

  #############################
  # InfluxDB Inputs
  #############################
  influxdb_endpoint_ip:
    description: >
      An IP Endpoint of your InfluxDB Cluster.
    type: string
    default: ''

  #############################
  # Management Worker Inputs
  #############################
  management_worker_max_workers:
    description: >
      Max number of celery workers.
    type: integer
    default: 100
  management_worker_min_workers:
    description: >
      Min number of celery workers.
    type: integer
    default: 2
